name: build docker image

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

env:
    DOCKER_BUILDKIT: 1

jobs:
    build_and_push_docker_image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to docker
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build and push docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                tags: my-registry/my-app:${{ github.sha }}
                    