name: CI - Build and Install

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Build project
      run: yarn build
    
    - name: Build Docker image
      run: |
        docker build -t abhibarkade/project-unkown-apie:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: abhibarkade
        password: nJw,f*bB2rX.XZ#
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push abhibarkade/project-unkown-api:latest
